# https://github.com/realm/SwiftLint#configuration

disabled_rules:
    - cyclomatic_complexity
    - file_length
    - function_body_length
    - function_parameter_count
    - notification_center_detachment
    - type_body_length
    - force_unwrapping
    - inclusive_language
    - line_length
    - force_cast
    - identifier_name
    - force_try
    - type_name

opt_in_rules:
    - force_unwrapping

custom_rules:
    open_brace_spacing:
        name: "Opening brace should be followed by space or newline"
        regex: '(\{[^\s^\}])'
        message: "Opening brace should be followed by space or newline"
        severity: warning
    close_brace_spacing:
        name: "Closing brace should be followed by space or newline"
        regex: '([^\s^\{]\})'
        message: "Closing brace should be followed by space or newline"
        severity: warning

identifier_name:
    excluded:
        - id
        - db

excluded:
    - Pods
    # Code from web
    - SendsaySDK/SendsaySDK/Classes/Others/Reachability.swift
    # Code from web
    - SendsaySDK/SendsaySDK/Classes/Others/NSManagedObjectContext+Perform.swift
    # Carthage checkouts
    - Carthage
    # SwiftSoup
    - SwiftSoup
